/**
 * expenses.js — API client module.
 *
 * WHY a dedicated API module?
 *   Centralises all fetch calls so:
 *   - Base URL changes in one place (env variable).
 *   - Retry / timeout logic is not duplicated.
 *   - Components never import `fetch` directly — easier to mock in tests.
 *
 * RETRY LOGIC:
 *   Network requests can fail transiently (TCP timeout, server restart).
 *   We retry up to MAX_RETRIES times with exponential backoff before giving up.
 *   POST requests include an Idempotency-Key so retries are safe.
 *
 * IDEMPOTENCY KEY STRATEGY:
 *   Generated once per form submission (not per retry).  If the user submits
 *   the form again after a failure, they get a fresh key (new logical request).
 *   Retries within the same submission share the same key.
 */

const BASE_URL = import.meta.env.VITE_API_BASE_URL || '';  // proxied in dev

const MAX_RETRIES  = 3;
const RETRY_DELAY  = 500;  // ms — doubles each retry (exponential backoff)

/**
 * sleep — Promise-based delay for retry backoff.
 */
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * apiFetch — Thin wrapper around fetch with:
 *   - Automatic JSON serialisation
 *   - Retry with exponential backoff for network errors and 5xx responses
 *   - Idempotency-Key header injection for POST requests
 *   - Consistent error shape: throws an Error with .data attached
 *
 * @param {string}  path       — e.g. '/expenses'
 * @param {object}  options    — fetch options (method, body, headers, idempotencyKey)
 * @param {number}  attempt    — internal retry counter
 */
async function apiFetch(path, options = {}, attempt = 1) {
  const { idempotencyKey, body, ...fetchOptions } = options;

  const headers = {
    'Content-Type': 'application/json',
    ...fetchOptions.headers,
  };

  if (idempotencyKey) {
    headers['Idempotency-Key'] = idempotencyKey;
  }

  let response;
  try {
    response = await fetch(`${BASE_URL}${path}`, {
      ...fetchOptions,
      headers,
      body: body ? JSON.stringify(body) : undefined,
      // AbortController timeout — prevents hanging indefinitely on a dead server.
      signal: AbortSignal.timeout(10_000),  // 10 s
    });
  } catch (networkErr) {
    // Network error (no response received) — retry.
    if (attempt <= MAX_RETRIES) {
      await sleep(RETRY_DELAY * Math.pow(2, attempt - 1));
      return apiFetch(path, options, attempt + 1);
    }
    throw new Error(`Network error after ${MAX_RETRIES} retries: ${networkErr.message}`);
  }

  const data = await response.json().catch(() => ({}));

  if (!response.ok) {
    // 4xx — client errors should NOT be retried (they won't succeed on retry).
    if (response.status >= 400 && response.status < 500) {
      const err = new Error(data?.error || data?.errors?.join(', ') || 'Request failed.');
      err.data   = data;
      err.status = response.status;
      throw err;
    }

    // 5xx — server errors, retry with backoff.
    if (attempt <= MAX_RETRIES) {
      await sleep(RETRY_DELAY * Math.pow(2, attempt - 1));
      return apiFetch(path, options, attempt + 1);
    }

    const err = new Error(data?.error || `Server error: ${response.status}`);
    err.data   = data;
    err.status = response.status;
    throw err;
  }

  return data;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * createExpense — POST /expenses
 *
 * @param {object} payload       — { amount, category, description, date }
 * @param {string} idempotencyKey — UUID v4 generated by the caller
 */
export function createExpense(payload, idempotencyKey) {
  return apiFetch('/expenses', {
    method:         'POST',
    body:           payload,
    idempotencyKey,
  });
}

/**
 * getExpenses — GET /expenses
 *
 * @param {object} params — { category?: string, sort?: string }
 */
export function getExpenses(params = {}) {
  const qs = new URLSearchParams();
  if (params.category) qs.set('category', params.category);
  if (params.sort)     qs.set('sort', params.sort);
  const query = qs.toString() ? `?${qs}` : '';
  return apiFetch(`/expenses${query}`, { method: 'GET' });
}

/**
 * getCategorySummary — GET /expenses/categories/summary
 */
export function getCategorySummary() {
  return apiFetch('/expenses/categories/summary', { method: 'GET' });
}
